shared-version = true
consolidate-commits = true
tag-name = "v{{version}}"
allow-branch = ["main"]
publish = false
push = false
pre-release-hook = ["git-cliff", "-o", "CHANGELOG.md", "--tag", "v{{version}}"]
