"""Generate the commissioning vocabulary (Rust enums + host Python tables) from
vocabulary.toml. Single source of truth; do not hand-edit the outputs."""

from __future__ import annotations

import argparse
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "shared/foci-firmware/src/commissioning/vocabulary.toml"
RUST_OUT = ROOT / "shared/foci-firmware/src/commissioning/vocabulary_generated.rs"
KLIPPER_OUT = ROOT / "host/klipper-foci/_vocabulary_generated.py"
TRACE_OUT = ROOT / "host/foci-trace/foci_trace/_vocabulary_generated.py"

RUST_HEADER = (
    "// @generated by tools/gen_commissioning_vocabulary.py from vocabulary.toml. Do not edit.\n\n"
)
PY_HEADER = (
    '"""@generated by tools/gen_commissioning_vocabulary.py from vocabulary.toml. '
    'Do not edit."""\n\n'
)
DERIVE = "#[derive(Debug, Clone, Copy, PartialEq, Eq, defmt::Format)]"

RUST_KEYWORDS = {
    "as",
    "break",
    "const",
    "continue",
    "crate",
    "dyn",
    "else",
    "enum",
    "extern",
    "false",
    "fn",
    "for",
    "if",
    "impl",
    "in",
    "let",
    "loop",
    "match",
    "mod",
    "move",
    "mut",
    "pub",
    "ref",
    "return",
    "self",
    "Self",
    "static",
    "struct",
    "super",
    "trait",
    "true",
    "type",
    "unsafe",
    "use",
    "where",
    "while",
    "async",
    "await",
    "abstract",
    "become",
    "box",
    "do",
    "final",
    "macro",
    "override",
    "priv",
    "typeof",
    "unsized",
    "virtual",
    "yield",
    "try",
}
REQUIRED = {
    "phase": {"ident", "wire_code", "label", "trace_ident", "doc"},
    "breakaway": {"ident", "wire_code", "label", "doc"},
    "workflow_shape": {"ident", "wire_code", "const_stem", "doc"},
    "action": {"ident", "wire_code", "label", "doc"},
}
EXPECTED_RESERVED = {
    "phase": [0, 9, 10, 11, 12, 13, 14, 15, 22, 23, 24, 25],
    "action": [0, 3, 4, 5, 6],
}

# Enum-level docs (fixed generator text, verbatim from the current source).
COMMISSION_ENUM_DOC = [
    "Identifies a single commissioning phase for progress reporting.",
    "",
    "Sent in the `foci_commission_phase` message on each phase transition.",
    "The Python module translates the `u8` code to a human-readable label.",
]
TO_U8_DOC = [
    "Encode to the wire representation used in the Klipper protocol message.",
    "",
    "Values are stable; new variants must use new codes. Code 9, formerly",
    "the retired mechanical-identification phase, and codes 10-15, formerly",
    "the two-variant velocity-tune block and the pre-renumber outer block,",
    "are never reused.",
]
REPR_ENUM = {
    "breakaway": (
        "BreakawayPhase",
        "pub(crate) ",
        ["Phase that owns a breakaway-campaign wire record or terminal."],
    ),
    "workflow_shape": (
        "VelocityAutotuneWorkflowKind",
        "pub ",
        ["Command-level acquisition shape disclosed before any motion."],
    ),
    "action": ("AutotuneAction", "pub ", ["Operator-selected velocity-autotune acquisition."]),
}


class ManifestError(Exception):
    """Raised when the manifest violates a validation rule."""


def load(path: Path = MANIFEST) -> dict:
    return tomllib.loads(path.read_text())


def validate(m: dict) -> None:
    reserved = m.get("reserved")
    if reserved != EXPECTED_RESERVED:
        raise ManifestError(f"[reserved] must be exactly {EXPECTED_RESERVED}")
    for group, required in REQUIRED.items():
        entries = m.get(group)
        if not isinstance(entries, list) or not entries:
            raise ManifestError(f"group '{group}' must be a non-empty array of tables")
        blocked = set(reserved.get(group, []))
        seen_codes: set[int] = set()
        seen_idents: set[str] = set()
        for e in entries:
            if not isinstance(e, dict):
                raise ManifestError(f"{group}: entry is not a table")
            if e.keys() != required:
                raise ManifestError(
                    f"{group}: entry {e.get('ident', '?')} keys {sorted(e.keys())} "
                    f"!= {sorted(required)}"
                )
            ident, code = e["ident"], e["wire_code"]
            if not isinstance(ident, str) or not ident.isidentifier() or ident in RUST_KEYWORDS:
                raise ManifestError(
                    f"{group}: '{ident}' is not a valid non-keyword Rust identifier"
                )
            if isinstance(code, bool) or not isinstance(code, int) or not 0 <= code <= 255:
                raise ManifestError(f"{group}: wire_code for {ident} must be int 0..=255")
            if code in blocked:
                raise ManifestError(f"{group}: wire_code {code} ({ident}) is reserved")
            if code in seen_codes or ident in seen_idents:
                raise ManifestError(f"{group}: duplicate code/ident near {ident}")
            for field in required - {"wire_code"}:
                if not isinstance(e[field], str):
                    raise ManifestError(f"{group}: {ident}.{field} must be a string")
            if group == "workflow_shape" and not e["const_stem"].isidentifier():
                raise ManifestError(f"{group}: const_stem '{e['const_stem']}' invalid")
            seen_codes.add(code)
            seen_idents.add(ident)


def _doc(lines, indent):
    return "".join(f"{indent}///{(' ' + ln) if ln else ''}\n" for ln in lines)


def _vdoc(doc, indent):
    return _doc(doc.strip().splitlines(), indent)


def _decl_order(entries):
    """Emit a #[cfg(test)] declaration-order inventory for one enum's impl body.

    Freezes the defmt::Format ordinal: variants are listed in manifest array
    order, and a pinned Rust test compares this against the frozen pre-change
    sequence, so reordering any enum (even one with explicit repr discriminants)
    fails the test."""
    lines = [
        "    /// Every variant in declaration order (the defmt::Format index).\n",
        "    #[cfg(test)]\n    pub(crate) const DECLARATION_ORDER: "
        "&'static [(&'static str, u8)] = &[\n",
    ]
    lines += [f'        ("{e["ident"]}", {e["wire_code"]}),\n' for e in entries]
    lines.append("    ];\n")
    return lines


def emit_rust(m: dict) -> str:
    o = [RUST_HEADER, _doc(COMMISSION_ENUM_DOC, ""), f"{DERIVE}\npub enum CommissionPhase {{\n"]
    for e in m["phase"]:
        o += [_vdoc(e["doc"], "    "), f"    {e['ident']},\n"]
    o += [
        "}\n\nimpl CommissionPhase {\n",
        _doc(TO_U8_DOC, "    "),
        "    pub fn to_u8(self) -> u8 {\n        match self {\n",
    ]
    for e in m["phase"]:
        o.append(f"            Self::{e['ident']} => {e['wire_code']},\n")
    o += ["        }\n    }\n\n"]
    o += _decl_order(m["phase"])
    o += ["}\n\n"]
    for group in ("breakaway", "workflow_shape", "action"):
        name, vis, edoc = REPR_ENUM[group]
        o += [_doc(edoc, ""), f"{DERIVE}\n#[repr(u8)]\n{vis}enum {name} {{\n"]
        for e in m[group]:
            o += [_vdoc(e["doc"], "    "), f"    {e['ident']} = {e['wire_code']},\n"]
        o += ["}\n\n", f"impl {name} {{\n"]
        o += _decl_order(m[group])
        o += ["}\n\n"]
    o += [
        "impl AutotuneAction {\n",
        "    /// Decode one wire action without assigning behavior to unknown values.\n",
        "    pub const fn from_u8(value: u8) -> Option<Self> {\n        match value {\n",
    ]
    for e in m["action"]:
        o.append(f"            {e['wire_code']} => Some(Self::{e['ident']}),\n")
    o += ["            _ => None,\n        }\n    }\n}\n"]
    return "".join(o)


def emit_klipper(m: dict) -> str:
    o = [PY_HEADER, "PHASE_NAMES: dict[int, str] = {\n"]
    o += [f"    {e['wire_code']}: {json.dumps(e['label'])},\n" for e in m["phase"]]
    o += ["}\n\nBREAKAWAY_PHASE_NAMES: dict[int, str] = {\n"]
    o += [f"    {e['wire_code']}: {json.dumps(e['label'])},\n" for e in m["breakaway"]]
    o += ["}\n\nACTION_CODES: dict[str, int] = {\n"]
    o += [f"    {json.dumps(e['label'])}: {e['wire_code']},\n" for e in m["action"]]
    o += ["}\n\n"]
    o += [f"{e['const_stem']} = {e['wire_code']}\n" for e in m["workflow_shape"]]
    o += [
        "\nWORKFLOW_SHAPE_TO_MATRIX_ORDER: dict[int, int] = {\n",
        "    SHAPE_MATRIX_ASCENDING: 1,\n    SHAPE_MATRIX_DESCENDING: 2,\n}\n",
    ]
    return "".join(o)


def emit_trace(m: dict) -> str:
    o = [PY_HEADER, "PHASE_NAMES: dict[int, str] = {\n"]
    o += [f"    {e['wire_code']}: {json.dumps(e['trace_ident'])},\n" for e in m["phase"]]
    o += ["}\n\nBREAKAWAY_PHASE_NAMES: dict[int, str] = {\n"]
    o += [f"    {e['wire_code']}: {json.dumps(e['label'])},\n" for e in m["breakaway"]]
    o += ["}\n"]
    return "".join(o)


TARGETS = [(RUST_OUT, emit_rust), (KLIPPER_OUT, emit_klipper), (TRACE_OUT, emit_trace)]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    m = load()
    validate(m)
    drift = False
    for path, emit in TARGETS:
        content = emit(m)
        if args.check:
            if (path.read_text() if path.exists() else "") != content:
                print(
                    f"drift: {path.relative_to(ROOT)} is stale; rerun the generator",
                    file=sys.stderr,
                )
                drift = True
        else:
            path.write_text(content)
    return 1 if drift else 0


if __name__ == "__main__":
    raise SystemExit(main())
